---
title: "MW Spatial Data Tutorial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Working with vector data 
### Load data and packages 
```{r}
library(sf)
library(tidyverse)

# Most sf functions use st_ as a prefix (spatial temporal)

--

# Load and look at data:

ak_shp_sf <- read_sf("shapefiles/ak_regions.shp")

plot(ak_shp_sf[1]) # gives you three because its plotting each column - not what you want 
 # also shows the aleutian islands on the wrong side of the map(because of projection)
ak_shp_sf # Console output tells you the bounding box (extent), epsg

```


### Transform the shape file:

```{r}

st_crs(ak_shp_sf) # check projection

# convert to an equal area projection: 
ak_shp_eq <- ak_shp_sf %>% 
  st_transform(crs = 3338) # can do a proj 4 string or an epsg code here 

# Re-check projection:
st_crs(ak_shp_eq)

plot(ak_shp_sf_eq[1]) # Now all the islands are together!


nrow(ak_shp_eq)
```

### sf and the tidyverse

```{r}

se <- ak_shp_eq %>% 
  select(region) %>%  # geometry is sticky; stays with the data unless you tell R otherwise
  filter(region == "Southeast")


plot(se[1])


# Bring in population information:

pop <- read_csv("shapefiles/alaska_population.csv")
head(pop) # has lat/long info 

# To plot this on a mac, we need to turn it into a simple feature 

pop_sf <- st_as_sf(pop,
                   coords = c('lng', 'lat'),
                   crs = 4326, # have to read in the data in the coordinate system it's already in, then you can transform it (this info is usually in metadata)
                   remove = F)

plot(pop_sf[1])


# Use st_transform to re-project population layer

pop_sf_eq <- pop_sf %>% 
  st_transform(crs = 3338)


# Now that the CRSs match, you can join population data to the regional data: 

pop_joined_sf <- st_join(pop_sf_eq, ak_shp_eq, join = st_within) # st_within

head(pop_joined_sf)
plot(pop_joined_sf)



```

### Use spatial data to create a data frame

```{r}

 # How many people live in each region?

pop_by_region <- pop_joined_sf %>% 
  as.data.frame() %>% 
  select(region_id, population) %>% 
  group_by(region_id) %>% 
  summarise(pop = sum(population))


# Add population information back to original shape file:
ak_pop_sf <- ak_shp_eq %>% 
  left_join(pop_by_region)

head(ak_pop_sf)

plot(ak_pop_sf["pop"])


```


### Group by and summarize

```{r}


# Calculate population by AK management area and map it:

pop_mgmt_area <- ak_pop_sf %>% 
  group_by(mgmt_area) %>% 
  summarise(pop = sum(pop), do_union = F) # do_union tells it whether or not to dissolve region boundaries

plot(pop_mgmt_area["pop"])

# Save the spatial object:

write_sf(ak_pop_sf, "shapefiles/ak_regions_population.shp")

```


## Working with raster data (GEOtiffs)
### Load data and packages
```{r}

library(rgdal)
library(raster)
library(sf) # using a shapefile to work with raster data; raster package is starting to accept sf objects

wc_rgns <- read_sf("shapefiles/wc_regions_clean.shp")
plot(wc_rgns)

```

### Raster data prep: Sea surface temperature 
```{r}

r <- raster("rasters/average_annual_sst_2008.tif") # this data is in K, we'll change it to C later
r
plot(r)
hist(r) # distribution of data in the raster


# Instead of reading in all the rasters at once, create a list of all the sst files:
sst_files <- list.files("rasters", pattern = "average_annual_sst", full.names = T) # finds everything that has sst in the file name; keeps full file names 


# Stack the rasters:
sst_stack <- stack(sst_files)
sst_stack
plot(sst_stack)

# Calculate average SST: 
sst_avg <- mean(sst_stack)-273.15 # conversion to C
plot(sst_avg)

# Another way to do it:
sst_avg <- calc(sst_stack, fun = function(x){mean(x) - 273.15}, progress = "text") # progress = text in raster functions helps you understand where your analysis is at (especially for long analyses)
plot(sst_avg)


```


### Raster data prep: Net primary productivity
```{r}

npp <- raster("rasters/annual_npp.tif")

plot(npp) # This is in Mollweide, need to convert back to what other raster layer is (lat/long)
# Getting more of the world than we need here, goin to crop and resample to make cells the same size

# 1. Re-project

npp_proj <- projectRaster(npp, crs = "+proj=longlat")  # preserve as much data from the original as possible 
npp_proj


# 2. Crop
npp_crop <- crop(npp_proj, sst_avg) # cropping to match sst_avg raster 
plot(npp_crop)

# 3. Resample
npp_res <- resample(npp_crop, sst_avg, method = "ngb") #nearest neighbor method!
plot(npp_res) # resolution is the same as sst_avg, but with original data retained


# Can also do this entire process using pipes:
 npp_res <- projectRaster(npp, crs = ("+proj=longlat")) %>% 
   crop(sst_avg) %>% 
   resample(sst_avg, method = "ngb")
   


```

### Analyze potential areas are for aquaculture

```{r}

stack(npp_res, sst_avg)


# Reclassify to ones (where aquaculture is possble) and zeroes (not possible for this species)

sst_pref <- reclassify(sst_avg, c(-Inf, 12, NA, # between neg infinitiy and 12, make it NA 
                                  12, 18, 1, 
                                  18, Inf, NA))


# Can then plot the feasible areas for temperature:

plot(sst_pref)


# Now do the same thing for npp:

npp_pref <- reclassify(npp_res, c(-Inf, 2.6, NA, # between neg infinitiy and 12, make it NA 
                                  2.6, 3, 1, 
                                  3, Inf, NA))
plot(npp_pref)


# Combine SST and NPP:

cells_pref <- npp_pref + sst_pref
plot(cells_pref) # looks okkay

# Better - overlay x and y:

cells_pref <- overlay(sst_pref, npp_pref, fun = function(x,y){x*y}, progress = "text")

plot(cells_pref) 
plot(wc_rgns, add = T, color=NA)  # run these two lines quickly! 



# Remove international waters
final_cells <- mask(cells_pref, wc_rgns)
plot(final_cells)


# More things you can do (in guiding doc): zonal statistics, 
```

```{r}

```













